In [1]:
import pandas as pd
import numpy as np

In [2]:
etfs = pd.read_excel('data/etf_base_assets.xlsx')

In [3]:
etfs

,ETF_Index,PROVIDER,ISIN,NOM,CAPITALISATION/DISTRIBUTION,ASSVIE,PEA,SFDR,HEDGED,FRAIS DE GESTION,...,FI_Yld_Field,FI_MD_Field,last_weekly_value,last_daily_value,WEEKLY_UPDATED,DAILY_UPDATED,Deriv?,hedge_vs_EUR_for_indices_for_backtests,FX_exposition,hedge_vs_EUR_for_indices_for_exp_returns
0,0,Blackrock,IE00B5BMR087,iShares Core S&P 500 UCITS ETF USD (Acc),C,-,N,6,N,0.07,...,NaN,NaN,442.87000,442.87000,OK,OK,NaN,EUR,EUR,hedged
1,1,Ssga,IE00BZ0G8C04,SPDR® MSCI Japan EUR Hdg UCITS ETF,C,-,N,6,Y,0.17,...,Yield_to_Worst,MODIFIED_DURATION,2363.24766,2363.24766,OK,OK,NaN,EUR,USD,-
2,2,Blackrock,IE00BKBF6H24,iShares Core MSCI World UCITS ETF EUR Hedged (...,D,-,N,6,Y,0.30,...,NaN,NaN,441.34000,441.34000,OK,OK,NaN,EUR,EUR,hedged
3,3,Blackrock,IE000OHHIBC6,iShares Core MSCI World UCITS ETF USD (Dist),D,-,N,6,N,0.20,...,NaN,NaN,478.96000,478.96000,OK,OK,NaN,EUR,EUR,hedged
4,4,Blackrock,IE00B4L5Y983,iShares Core MSCI World UCITS ETF,C,-,N,6,N,0.20,...,NaN,NaN,478.96000,478.96000,OK,OK,NaN,EUR,EUR,hedged
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1978,2351,Dws,IE00074JLU02,Xtrackers (IE) PlcJapan Net Zero Pathway Paris...,C,-,N,8,N,0.15,...,NaN,NaN,3820.62437,3820.62437,OK,OK,NaN,EUR,JPY,-
1979,2352,Dws,LU0292100046,XtrackersMSCI Korea UCITS ETF 1C,C,-,N,6,N,0.45,...,NaN,NaN,3820.62437,3820.62437,OK,OK,NaN,EUR,JPY,-
1980,2354,Dws,IE0006FDYJF8,Xtrackers (IE) PlcMSCI Japan Climate Transitio...,D,-,N,8,N,0.15,...,NaN,NaN,3820.62437,3820.62437,OK,OK,NaN,EUR,JPY,-
1981,2357,Dws,LU0322252924,XtrackersFTSE Vietnam Swap UCITS ETF 1C,C,-,N,6,N,0.85,...,NaN,NaN,3820.62437,3820.62437,OK,OK,NaN,EUR,JPY,-
1982,2358,Dws,LU0476289623,XtrackersMSCI Indonesia Swap UCITS ETF 1C,C,-,N,6,N,0.65,...,NaN,NaN,3820.62437,3820.62437,OK,OK,NaN,EUR,JPY,-

In [4]:
etfs.columns

Index(['ETF_Index', 'PROVIDER', 'ISIN', 'NOM', 'CAPITALISATION/DISTRIBUTION',
       'ASSVIE', 'PEA', 'SFDR', 'HEDGED', 'FRAIS DE GESTION', 'FRAIS E/S',
       'ENCOURS SOUS GESTION', 'DEVISE AUM', 'DEVISE ETF', 'CHANGE',
       'ENCOURS SOUS GESTION (EUR)', 'CLASSE 1', 'CLASSE 2', 'CLASSE 3',
       'CLASSE 4', 'CLASSE 5', 'LIEN', 'LIEN TEXTE', 'XTB', 'ING', 'SCALABLE',
       'EASYBOURSE', 'BOURSO', 'BOURSEDIRECT', 'ETORO', 'ETF_ISIN_x',
       'ETF_Name', 'ETF_Classe_1', 'ETF_Classe_2', 'ETF_Classe_3',
       'ETF_Classe_4', 'ETF_Classe_5', 'Asset_Index', 'Asset_Name',
       'Asset_ETF_Name', 'Asset_Class', 'Asset_Geo_Area', 'Asset_Ticker',
       'Match_Score', '#', 'Name', 'Name_BBG', 'Name_report', 'Asset_class',
       'Ticker_analysis', 'Ticker_PORT_perf', 'ETF_ticker', 'ETF_bbg_name',
       'ETF_CCY', 'ETF_ISIN_y', 'EQY_Price_Ticker', 'Geo_Area',
       'EXP_MACRO_RETURN', 'geo_exp_real_growth', 'geo_exp_inflation',
       'LT_hedging_cost', 'EPS', 'Price', 'P/E', 'P/E (direct)', 'Earn_yld',
       'Exp_Eqy_return', 'Stock_Dur_3', 'Exp_ILB_return', 'Exp_other_return',
       'FI_Yld_Ticker', 'FI_MD_Ticker', 'Index', 'Yld', 'Dur', 'Sensi',
       'Index_SD', 'Yld_SD', 'Sensi_SD', 'FX', 'FX_forced', 'FX_final', '#.1',
       'FI_Yld_Field', 'FI_MD_Field', 'last_weekly_value', 'last_daily_value',
       'WEEKLY_UPDATED', 'DAILY_UPDATED', 'Deriv?',
       'hedge_vs_EUR_for_indices_for_backtests', 'FX_exposition',
       'hedge_vs_EUR_for_indices_for_exp_returns'],
      dtype='object')

In [5]:
list(np.unique(etfs['CLASSE 1']))

['bonds', 'cash', 'commodities', 'equities', 'securitized']

In [6]:
list(np.unique(etfs['CLASSE 2']))

['aggregate',
 'cash',
 'commodities',
 'core',
 'corporate',
 'emerging',
 'government',
 'leverage',
 'private',
 'sector',
 'short',
 'smartbeta',
 'thematic']

In [22]:
indices_prices = pd.read_excel('data/quotes.xlsx', sheet_name='indices', index_col=0, parse_dates=True)
indices_prices.index = pd.to_datetime(indices_prices.index, format='%Y-%m-%d')

In [24]:
mapping = pd.read_excel('data/quotes.xlsx', sheet_name='mapping', index_col=0)
mapping

                       Asset
ETF
IE00B5BMR087   SPXUXEN Index
IE00BZ0G8C04    NDDLJN Index
IE00BKBF6H24  MXWOHEUR Index
IE000OHHIBC6    NDDUWI Index
IE00B4L5Y983    NDDUWI Index
...                      ...
IE00074JLU02  M0JPHEUR Index
LU0292100046  M0JPHEUR Index
IE0006FDYJF8  M0JPHEUR Index
LU0322252924  M0JPHEUR Index
LU0476289623  M0JPHEUR Index

[1896 rows x 1 columns]

In [ ]:
etf_prices = pd.read_excel('data/quotes.xlsx', sheet_name='etfs', index_col=0, parse_dates=True)
etf_prices.index = pd.to_datetime(etf_prices.index, format='%Y-%m-%d')

In [21]:


# ou masque booléen
indices_prices[indices_prices.index.year == 2020]

,SPXUXEN Index,NDDLJN Index,MXWOHEUR Index,NDDUWI Index,M4EUSI Index,CBSE NA Equity,IEAC LN EQUITY,UE27 NA Equity,M0JPHEUR Index,M1USMMT Index,...,M00IEF$O Index,DBMMFED1 Index,M7JPSC Index,IBOXUSLT Index,M1EF000V Index,LEATTREU Index,M1EFMMT Index,LF94TREH Index,LUATTRUU Index,I22547EU Index
Date,,,,,,,,,,,,,,,,,,,,,
2020-12-25,5464.560,2195.536,279.98,7915.112,2498.57,14.939,136.240,17.771,236.03,3822.834,...,1946.90,182.9767,303.50,155.2730,574.68,285.3488,12947.12,281.6037,2555.72,285.0961
2020-12-18,5473.750,2214.884,280.48,7935.059,2510.11,14.955,136.470,17.743,238.11,3836.215,...,1947.74,182.9740,304.22,155.6053,575.38,286.1536,12793.53,282.7950,2551.40,285.9111
2020-12-11,5407.818,2199.573,276.73,7801.141,2459.78,14.973,136.550,17.750,236.49,3693.560,...,1925.48,182.9708,302.55,153.9795,566.88,287.3113,12541.84,283.7258,2560.29,287.2727
2020-12-04,5460.023,2193.591,278.42,7852.990,2470.14,14.955,136.330,17.841,235.87,3703.150,...,1923.77,182.9676,301.45,154.6743,565.23,285.1822,12514.77,280.2102,2544.76,285.3066
2020-11-27,5371.296,2204.863,275.24,7736.576,2482.09,14.938,136.170,17.813,237.11,3674.650,...,1901.82,182.9645,303.01,153.4186,554.23,286.1508,12546.92,280.7822,2564.45,286.1589
2020-11-20,5257.076,2126.990,269.40,7552.231,2454.60,14.920,135.975,17.830,229.05,3576.266,...,1891.00,182.9617,295.90,153.6512,541.89,286.0317,12569.15,278.7010,2567.85,286.1983
2020-11-13,5297.631,2096.111,268.79,7518.606,2446.00,14.859,135.410,17.630,225.71,3574.085,...,1868.70,182.9585,294.75,152.8072,532.83,285.0262,12561.41,276.4555,2554.59,285.3904
2020-11-06,5184.600,2033.417,261.83,7339.426,2334.45,14.846,135.425,17.795,219.13,3652.045,...,1836.89,182.9553,292.09,150.3623,514.84,285.8502,12660.77,278.3675,2562.40,286.8400
2020-10-30,4835.538,1933.902,244.67,6811.780,2182.23,14.720,134.550,17.490,208.45,3341.231,...,1746.27,182.9521,280.06,146.4723,482.75,285.4960,11487.48,279.4306,2556.44,287.0718
2020-10-23,5123.580,1987.596,258.56,7219.402,2330.32,14.769,134.780,17.426,214.44,3533.859,...,1795.41,182.9489,289.36,147.5664,505.37,284.0145,11443.45,279.5697,2555.36,285.9233
2020-10-16,5152.967,1978.741,260.26,7247.082,2379.79,14.828,134.830,17.680,213.48,3612.987,...,1784.05,182.9457,288.16,149.3953,494.83,285.8315,11750.03,281.4435,2570.56,287.1126
2020-10-09,5141.593,2011.986,260.59,7269.131,2397.21,14.660,134.440,17.559,217.10,3592.611,...,1791.63,182.9425,294.42,148.8876,495.96,284.0682,11669.18,278.7118,2564.14,285.2713
2020-10-02,4951.810,1965.423,252.00,7013.771,2343.51,14.713,133.950,17.603,212.06,3448.951,...,1746.03,182.9393,286.96,146.4915,481.86,283.3237,11080.30,278.9537,2577.03,285.2306
2020-09-25,4873.051,1980.323,248.68,6902.629,2306.54,14.654,133.390,17.349,213.73,3406.071,...,1717.35,182.9361,290.21,145.6966,473.93,282.7060,10893.45,278.8857,2585.30,285.1667
2020-09-18,4910.350,1994.256,251.60,7023.556,2386.10,14.695,133.920,17.590,215.24,3377.620,...,1782.84,182.9329,291.52,148.0875,499.71,281.6845,11362.65,279.7192,2578.68,284.4442
2020-09-11,4941.433,1990.251,252.18,7022.474,2380.93,14.658,133.670,17.636,214.72,3341.976,...,1760.09,182.9297,284.93,148.6119,491.71,280.8191,11160.25,280.1827,2583.07,284.2722
2020-09-04,5070.016,1972.870,255.32,7114.624,2326.98,14.619,133.600,17.650,212.85,3461.290,...,1766.19,182.9265,279.53,149.3332,492.82,280.4577,11575.82,277.0537,2572.81,284.2666
2020-08-28,5192.250,1958.486,260.71,7281.769,2362.24,14.541,133.500,17.401,211.42,3573.886,...,1792.05,182.9233,276.23,147.7021,500.80,279.1843,11881.91,277.5241,2569.83,282.8648
2020-08-21,5031.026,1956.952,254.84,7087.902,2344.96,14.616,133.780,17.716,211.31,3487.727,...,1770.18,182.9201,276.74,148.8068,494.33,281.3400,11343.90,277.4916,2586.61,284.6887
2020-08-14,4993.160,1980.777,253.80,7062.163,2352.29,14.555,133.275,17.639,213.78,3366.420,...,1768.69,182.9167,278.22,148.8246,500.17,279.7968,11123.39,276.4608,2575.13,282.9857
2020-08-07,4960.845,1889.125,250.89,6975.410,2328.28,14.648,133.720,18.080,203.99,3354.230,...,1747.67,182.9132,266.46,149.9563,492.66,281.7025,11463.77,280.6368,2601.81,284.7747
2020-07-31,4841.235,1829.189,245.22,6822.597,2284.63,14.575,133.080,17.958,197.53,3309.706,...,1739.70,182.9096,258.15,148.2605,488.59,281.0258,11205.59,281.3644,2605.74,285.3222
2020-07-24,4766.567,1919.784,244.93,6781.781,2357.54,14.555,132.950,17.977,207.09,3235.721,...,1713.25,182.9062,271.12,147.0727,485.40,279.8656,10732.75,279.4062,2596.69,283.5858
2020-07-17,4784.209,1920.291,246.62,6787.834,2391.83,14.482,132.445,17.836,207.18,3279.983,...,1718.94,182.9029,270.40,144.9962,485.77,278.8319,10614.00,276.6437,2586.18,283.7136
2020-07-10,4727.948,1877.664,243.15,6685.366,2354.65,14.415,132.460,17.693,202.62,3294.732,...,1730.06,182.8996,263.21,143.7545,489.33,278.9180,11073.48,276.1868,2584.90,284.0846
2020-07-03,4647.484,1894.696,240.16,6585.251,2344.73,14.400,132.175,17.545,204.48,3158.927,...,1702.21,182.8964,267.20,144.1632,478.06,277.7170,10418.54,277.9167,2573.50,283.3329
2020-06-26,4468.270,1917.012,233.02,6377.243,2311.93,14.347,131.480,17.345,206.89,3011.105,...,1660.65,182.8935,274.15,142.9987,462.77,278.1288,9972.81,276.7960,2579.69,284.0050
2020-06-19,4599.798,1922.035,238.47,6529.276,2350.03,14.408,131.835,17.306,207.45,3059.723,...,1664.19,182.8905,274.15,142.9360,466.65,276.9603,9735.56,274.8792,2566.67,282.8125
2020-06-12,4516.095,1910.488,233.43,6396.202,2260.03,14.284,131.890,17.096,206.20,2934.610,...,1654.22,182.8875,271.20,140.9231,460.93,275.6384,9307.41,273.9890,2567.71,282.5866
2020-06-05,4737.585,1957.432,244.18,6696.194,2385.17,14.383,132.890,17.054,211.06,2984.406,...,1676.11,182.8849,279.33,141.3308,473.28,273.3557,9185.93,270.8695,2534.76,279.1295
2020-05-29,4518.959,1894.206,232.41,6343.310,2247.49,14.200,130.400,17.110,204.47,2969.498,...,1598.66,182.8830,273.72,138.4113,436.19,275.3408,8745.43,274.2707,2573.89,282.4321
2020-05-22,4389.954,1785.436,225.26,6117.666,2191.11,14.066,129.030,17.031,193.11,2914.572,...,1562.82,182.8812,260.80,138.5856,423.55,274.2202,8484.67,272.3361,2575.80,283.0448
2020-05-15,4251.112,1758.662,218.55,5927.186,2116.96,13.941,128.480,16.583,190.24,2883.617,...,1561.32,182.8794,253.93,134.3670,419.22,272.9232,8598.55,270.6242,2581.35,283.8128
2020-05-08,4349.285,1767.158,223.52,6081.664,2166.69,14.045,129.195,16.616,191.18,2866.560,...,1578.61,182.8776,254.68,133.5567,429.31,272.4372,8418.12,270.7260,2570.83,283.8380
2020-05-01,4201.389,1733.280,217.07,5909.753,2160.09,14.194,129.650,16.910,187.48,2732.907,...,1604.15,182.8758,248.27,132.3998,435.57,274.7687,8152.12,268.8897,2578.48,284.6095
2020-04-24,4213.239,1722.163,216.08,5856.720,2108.76,13.985,129.110,16.904,186.20,2760.705,...,1535.69,182.8742,244.02,130.0717,412.09,271.5161,7842.88,268.8404,2588.02,282.1168
2020-04-17,4267.977,1755.555,218.88,5943.246,2119.79,13.920,128.520,17.035,189.88,2791.357,...,1550.90,182.8725,244.12,131.9213,423.29,272.3354,7913.06,267.2275,2576.64,282.2831
2020-04-10,4140.534,1737.653,213.92,5808.056,2094.40,13.738,128.900,16.483,187.92,2626.009,...,1542.27,182.8707,241.62,130.8689,424.67,271.6408,7789.74,268.4023,2566.62,279.8402
2020-04-03,3688.758,1613.331,193.38,5232.131,1978.80,13.492,124.950,15.935,174.34,2383.849,...,1454.42,182.8689,220.99,127.5682,397.11,272.8448,7109.00,266.4395,2582.96,281.4765
2020-03-27,3776.656,1748.939,198.17,5373.875,1973.67,13.589,125.690,15.998,189.27,2511.176,...,1458.81,182.8660,244.41,130.1625,400.30,275.5536,7221.59,266.2320,2562.64,282.0906
2020-03-20,3394.108,1535.517,180.21,4854.303,1853.29,13.172,123.000,14.065,166.12,2217.875,...,1408.33,182.8613,210.15,122.6672,381.27,272.8899,6720.43,254.3053,2519.92,279.5211
2020-03-13,4030.188,1532.116,203.69,5530.735,1865.29,14.040,128.210,15.363,165.61,2662.774,...,1520.66,182.8397,208.72,135.4569,427.20,274.9629,7643.57,261.3485,2512.58,285.1819
2020-03-06,4414.587,1785.730,229.87,6314.628,2255.32,14.695,133.800,17.273,193.18,2922.883,...,1692.34,182.8009,250.27,151.7860,489.59,282.6774,8798.18,276.4336,2562.15,288.7519
2020-02-28,4389.046,1829.684,230.81,6287.117,2273.77,14.514,133.960,16.857,197.86,2833.380,...,1665.22,182.7497,256.19,148.9398,489.35,280.6664,8708.34,271.7370,2492.04,286.4713
2020-02-21,4967.202,2021.305,259.84,7051.480,2561.17,14.833,135.150,16.916,218.89,3174.616,...,1768.18,182.6935,286.13,153.4463,529.42,280.2365,9534.03,271.2672,2439.24,283.4659
2020-02-14,5032.872,2049.054,262.55,7133.226,2569.65,14.743,135.040,16.815,221.96,3214.388,...,1784.54,182.6373,294.54,152.4812,539.34,278.9825,9553.92,268.8539,2420.68,282.8692
2020-02-07,4951.701,2081.797,259.30,7051.803,2543.07,14.780,134.700,16.782,225.46,3128.083,...,1785.54,182.5812,298.86,152.1026,534.43,278.2643,9313.29,268.9624,2420.93,282.3699
2020-01-31,4799.478,2023.556,251.61,6867.603,2449.81,14.790,135.160,16.767,219.18,3059.419,...,1763.65,182.5247,292.11,151.7873,522.75,279.3253,9176.58,269.3374,2427.69,283.5360
2020-01-24,4906.872,2076.061,257.74,7021.584,2525.88,14.718,134.540,16.671,224.97,3100.800,...,1836.33,182.4695,300.69,150.4262,554.97,275.8099,9592.25,268.6370,2405.37,281.2390
2020-01-17,4959.148,2081.732,259.80,7079.987,2523.20,14.647,133.970,16.522,225.57,3085.938,...,1866.08,182.4145,301.38,150.3273,569.89,273.3052,9767.96,266.0274,2380.96,279.0771
2020-01-10,4863.584,2076.702,255.55,6968.134,2492.04,14.628,134.280,16.518,225.02,2996.193,...,1846.08,182.3599,303.29,149.2429,563.32,273.6163,9593.80,264.2031,2381.76,278.8521
2020-01-03,4818.177,2056.953,253.43,6924.025,2482.40,14.675,134.720,16.504,222.91,2957.444,...,1845.02,182.3049,303.08,148.4992,564.03,274.3794,9516.08,266.0367,2386.77,279.8403

In [10]:
indices_prices.dtypes

Date               datetime64[ns]
SPXUXEN Index             float64
NDDLJN Index              float64
MXWOHEUR Index            float64
NDDUWI Index              float64
M4EUSI Index              float64
CBSE NA Equity            float64
IEAC LN EQUITY            float64
UE27 NA Equity            float64
M0JPHEUR Index            float64
M1USMMT Index             float64
M1US000V Index            float64
LQDE IM Equity            float64
BCIT1T Index              float64
MACXUIGB Index            float64
NDDUUS Index              float64
M1USSC Index              float64
M1USMVOL Index            float64
JPEICORE Index            float64
M0USHEUR Index            float64
M7EU Index                float64
JNKE FP EQUITY            float64
UC97 LN Equity            float64
STHE IM Equity            float64
M1USQU Index              float64
DBDCONIA Index            float64
IHYU LN Equity            float64
NDUEEGF Index             float64
M4JPSI Index              float64
M7EU000V Index            float64
M7EUSC Index              float64
MAEUVOE Index             float64
M1CXJPJ Index             float64
IBOXIG Index              float64
IHYG LN Equity            float64
MAEUMMT Index             float64
BEUSGA Index              float64
M1USSI Index              float64
M7EUQU Index              float64
TPXDDVD Index             float64
M1WD Index                float64
USYH IM EQUITY            float64
M1EMS Index               float64
CBUSE IM EQUITY           float64
NDDUPXJ Index             float64
SCXR Index                float64
M1EFSC Index              float64
M00IEF$O Index            float64
DBMMFED1 Index            float64
M7JPSC Index              float64
IBOXUSLT Index            float64
M1EF000V Index            float64
LEATTREU Index            float64
M1EFMMT Index             float64
LF94TREH Index            float64
LUATTRUU Index            float64
I22547EU Index            float64
dtype: object